version: 0.0
os: windows
files:
  - source: src\Test-For-AWS\bin\release\netcoreapp3.1\publish\
    destination: C:\inetpub\wwwroot
file_exists_behavior: OVERWRITE
hooks:
  ApplicationStop:
    - location: scripts/stop-app.ps1
      timeout: 300
      runas: Administrator
  ApplicationStart:
    - location: scripts/start-app.ps1
      timeout: 300
      runas: Administrator
