version: 0.0
os: windows
files:
  - source: bin\release\net6.0\publish\
    destination: C:\inetpub\App
file_exists_behavior: OVERWRITE
hooks:
  ApplicationStop:
    - location: deploy-scripts/stop-app.ps1
      timeout: 300
      runas: Administrator
  ApplicationStart:
    - location: deploy-scripts/start-app.ps1
      timeout: 300
      runas: Administrator
